name: SlimUNETR
args:
  shrink: false
  in_channels: 1
  out_channels: 1
  embed_dim: 96 
  embedding_dim: 8 #1, 8, 27, 64, 216, (256)
  channels: [ 24, 48, 60 ]
  blocks: [ 1, 2, 3, 2 ]
  heads: [ 1, 2, 4, 4 ]
  r: [ 4, 2, 2, 1 ]
  dropout: 0.3