generation:
  direct_path: null
  epoch: best
  weight_path: train
inference:
  direct_path: null
  epoch: best
  weight_path: train
run:
  checkpoint: First_Det_lab[1]_[128]_lr[0.0000125]_res34
  device_num: "0"
  loader:
    target_labels:
      - 1
    batch_size: 4
    drop_last: true
    num_workers: 4
    pin_memory: true
    detector: true
    dataset:
      name: amos22
      root: /home/work/.dataset/Amos22_RAS/
      scale: 128
      image_scale: 128
      label_scale: 128
      slice_scale: 128
      bbox_scale: 128
  model:
    args:
      args:
        backbone_name: resnet34 #50
        dilation: False
        position_embedding: sine    #sine, learned
        enc_layers: 6
        dec_layers: 6
        dim_feedforward: 2048
        hidden_dim: 256
        dropout: 0.1
        nheads: 8
        num_queries: 3 #1
        pre_norm: True
        aux_loss: False
        num_classes: 3
        lr_backbone: 0.00001
        masks: False
    name: DETR
    type: det #det, seg, comb
  work_dir: /home/work/jayeon/result/roi_dyseg/
train:
  loss:
      DETR_Criterion:
        matcher:
          cost_class: 1
          cost_bbox: 5
          cost_giou: 2
        weight_dict:
          loss_ce: 1
          loss_bbox: 5
          loss_giou: 2
        eos_coef: 0.1
        losses: [labels, boxes, cardinality]


  metrics:
    DiceMetric:
      include_background: true
      reduction: mean_batch
      get_not_nans: false
    HausdorffDistanceMetric:
      percentile: 95
      include_background: true
      reduction: mean_batch
      get_not_nans: false
    MeanIoU:
      include_background: true
      reduction: mean_batch
      get_not_nans: false
  optimizer:
    betas:
    - 0.9
    - 0.95
    lr: 0.0000125 #0.002 #0.0025
    opt: adamw
    weight_decay: 0.05
  resume: null
  save_cycle: 200
  scheduler:
    max_epochs: 1000
    warmup_epochs: 5
