checkpoint: First
work_dir: /home/work/jayeon/result/roi_dyseg/
device_num: "0"
model: 
  yml_path: ROI_DySeg.yml #SlimUNETR_128.yml #16, 32, 64, 128
loader: 
  yml_path: default_lab15.yml  #1, 3, 4, 6, 7, 12, 15
  dataset: 
    yml_path: amos22_16.yml